### ISSUE TITLE
How Do I Contact You

### ISSUE THREAD

**Issue by kivo360** [jmcph4/PyOBSim#1]
Hi!

I found your project recently and I was wondering about how I could contact you. One of the things I want to do 2019 is create a full super multi-agent market simulator.

I figure creating the simulator would be difficult but powerful over-time if we have reinforcement learning to try learning from repeated simulations.

**Comment by kivo360** [comment]
Shit. The way I did this was really creepy. Hey, I saw you were messing a lot with rust recently (I'm a follower). Are you doing anything in particular with it?

I'm personally thinking of creating a programming language with it.

**Comment by kivo360** [comment]
Still, how do I contact you?

**Comment by jmcph4** [comment]
@kivo360 Via [email](mailto:jmcph4.github@gmail.com).
